apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: from-temp-hello-world-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: sample-template
              template: hello-world
